const puzzloopredball = Item("puzzloop-red-ball");
puzzloopredball.color = Color.valueOf("ff0000");
const puzzloopgreenball = Item("puzzloop-green-ball");
puzzloopgreenball.color = Color.valueOf("00BB00");
const puzzloopblueball = Item("puzzloop-blue-ball");
puzzloopblueball.color = Color.valueOf("0022FF");
const puzzloopyellowball = Item("puzzloop-yellow-ball");
puzzloopyellowball.color = Color.valueOf("FFFF00");
const puzzloopcyanball = Item("puzzloop-cyan-ball");
puzzloopcyanball.color = Color.valueOf("00DDFF");
const puzzlooppurpleball = Item("puzzloop-purple-ball");
puzzlooppurpleball.color = Color.valueOf("DD55FF");
const puzzlooporangeball = Item("puzzloop-orange-ball");
puzzlooporangeball.color = Color.valueOf("FFAA00");
const puzzloopgrayball = Item("puzzloop-gray-ball");
puzzloopgrayball.color = Color.valueOf("666666");
puzzloopredball.explosiveness = puzzloopgreenball.explosiveness = puzzloopblueball.explosiveness = puzzloopyellowball.explosiveness = puzzloopcyanball.explosiveness = puzzlooppurpleball.explosiveness = puzzlooporangeball.explosiveness = puzzloopgrayball.explosiveness = 1;
puzzloopredball.flammability = puzzloopgreenball.flammability = puzzloopblueball.flammability = puzzloopyellowball.flammability = puzzloopcyanball.flammability = puzzlooppurpleball.flammability = puzzlooporangeball.flammability = puzzloopgrayball.flammability = 0;
puzzloopredball.radioactivity = puzzloopgreenball.radioactivity = puzzloopblueball.radioactivity = puzzloopyellowball.radioactivity = puzzloopcyanball.radioactivity = puzzlooppurpleball.radioactivity = puzzlooporangeball.radioactivity = puzzloopgrayball.radioactivity = 0;
puzzloopredball.charge = puzzloopgreenball.charge = puzzloopblueball.charge = puzzloopyellowball.charge = puzzloopcyanball.charge = puzzlooppurpleball.charge = puzzlooporangeball.charge = puzzloopgrayball.charge = 0;